name: CI

on:
  push:
    branches: ["SpaceBattle"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore SpaceBattle.Lib.Tests

      - name: Install Required Tools
        run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-coverage
          dotnet tool install coverlet.console

      - name: Run the unit tests with code coverage
        run: cd SpaceBattle.Lib.Tests && dotnet dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
      - name: Coverage
        run: dotnet coverlet SpaceBattle.Lib.Tests/bin/Debug/net7.0/SpaceBattle.Lib.Tests.dll --target "dotnet" --targetargs "test --no-build" -f=opencover -o="coverage.xml"
      
